title: A-Z
tagline: Din personlige rejse gennem viden og teknik
description: En platform af niknak - dedikeret til innovation og systematik.
url: "https://niknakhub.github.io"
baseurl: ""

author:
  name: niknak
  github: niknakhub
  twitter: niknakhub

avatar: https://github.com

lang: da
timezone: Europe/Copenhagen
theme: jekyll-theme-chirpy

paginate: 10

kramdown:
  syntax_highlighter: rouge
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
