title: A-Z
tagline: Klassisk innovation og systematik
description: En platform af niknak - dedikeret til teknisk præcision.
url: "https://niknakhub.github.io"
baseurl: ""

author:
  name: niknak
  github: niknakhub
  twitter: niknakhub

# Design-agentens visuelle identitet
avatar: https://github.com
theme_mode: dark # Sætter en stilfuld mørk baggrund som standard

lang: da
timezone: Europe/Copenhagen
theme: jekyll-theme-chirpy

# Klassisk menu-struktur (Vi fjerner Archives og Tags for et rent look)
tabs:
  - home
  - categories
  - about

paginate: 10

kramdown:
  syntax_highlighter: rouge
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
